version: '3.4'

services:
  release-note:
    image: docker.items.com/release-note
    container_name: release-note
    build: .
    command: tail -f /dev/null
    volumes:
      - ./app:/app
    # environment:
    #   HADOOP_NAMENODE_URL: 192.168.1.7
    # dns: 
    #   - 192.168.1.4
